name: Deploy web app to Azure Static Web Apps

on:
  workflow_call:
    inputs:
      app-location:
        required: false
        type: string
        default: "/"
      api-location:
        required: false
        type: string
        default: "api"
      app-artifact-location:
        required: false
        type: string
        default: "build"
    secrets:
      azure-static-web-apps-api-token:
        required: true
      gh-token:
        required: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.azure-static-web-apps-api-token }}
          repo_token: ${{ secrets.gh-token }}
          action: "upload"
          app_location: ${{ inputs.app-location }}
          api_location: ${{ inputs.api-location }}
          app_artifact_location: ${{ inputs.app-artifact-location }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.azure-static-web-apps-api-token }}
          action: "close"
          app_location: ${{ inputs.app-location }}
